### ISSUE TITLE
[ROS2] Binaries do not properly export models / world paths

### ISSUE THREAD

**Issue by SteveMacenski** [aws-robotics/aws-robomaker-small-warehouse-world#19] opened 2021-12-01 20:53 UTC
Launching the default example after installing the package

```
ros2 launch aws_robomaker_small_warehouse_world small_warehouse.launch.py
```

it fails to load because it cannot find the models or world files. This makes the package currently unusable since none of the launch files or loading of world / model files works properly.

**Comment by SteveMacenski** [comment] 2021-12-01 22:11
Only got it to work once I explicitly filed the paths into tha gazebo model path

```
export GAZEBO_MODEL_PATH=$GAZEBO_MODEL_PATH:/opt/ros/rolling/share/aws_robomaker_small_warehouse_world:/opt/ros/rolling/share/aws_robomaker_small_warehouse_world/models:/opt/ros/rolling/share/aws_robomaker_small_warehouse_world/worlds
```

**Comment by SteveMacenski** [comment] 2021-12-08 20:31
@cheng-kevin this is a problem making your release incorrect

**Comment by ahtsan** [comment] 2021-12-10 22:02
Hi @SteveMacenski. One of the instructions in the README is to run "export GAZEBO_MODEL_PATH=`pwd`/models" before loading the world

**Comment by SteveMacenski** [comment] 2021-12-10 22:48
That's not a valid solution - that's broken if its not properly exported. If that's the solution, you should remove the binaries because they cannot be used.

**Comment by ahtsan** [comment] 2021-12-10 22:50
Do you have any recommendation/existing references on how to export custom models properly?

**Comment by SteveMacenski** [comment] 2021-12-13 18:19
From reading the migration guide https://github.com/ros-simulation/gazebo_ros_pkgs/wiki/ROS-2-Migration:-Gazebo-ROS-Paths, it sounds like there are 2 options:

-   Export properly + use the GazeboRosPaths script to concat in the launch file (or use the `gazebo.launch.py` file)
-   Export properly + use the dsv files and it automatically sets up on sourcing.

The second feels like the best solution so that we’re not tied to a specific launch file and it “just works”.

**Comment by ahtsan** [comment] 2021-12-14 18:35
Looks like it's already exported ([ref](https://github.com/aws-robotics/aws-robomaker-small-warehouse-world/blob/ros2/package.xml#L20)) and there's a [dsv](https://github.com/aws-robotics/aws-robomaker-small-warehouse-world/blob/ros2/env-hooks/aws_robomaker_small_warehouse_world.dsv.in) file already.

**Comment by SteveMacenski** [comment] 2021-12-14 21:58
I'd recommend going slower and looking at the full list of what is needed. At bare minimum, you're not actually registering and/or installing it https://github.com/ros-simulation/gazebo_ros_pkgs/blob/ros2/gazebo_plugins/CMakeLists.txt#L493 (example). There may be more you need to do, I'm not sure. 

You're definitely also missing exporting of `worlds` in the package.xml file.

**Comment by SteveMacenski** [comment] 2021-12-14 22:00
It's not working and I think you said that you can see that on your side as well.  It looks like it should be OK to me, but clearly its not working.

**Comment by ahtsan** [comment] 2021-12-15 00:14
I think the issue is that we are not using `gazebo_ros` in the launch files. After merging [this PR](https://github.com/aws-robotics/aws-robomaker-small-warehouse-world/pull/20) we will bloom release again and hopefully it works.

**Comment by SteveMacenski** [comment] 2021-12-15 02:57
Sounds good!

**Comment by lucabonamini** [comment] 2021-12-21 07:01
When the new binaries will be available?

**Comment by ahtsan** [comment] 2021-12-21 19:07
In https://github.com/ros/rosdistro/blob/master/foxy/distribution.yaml#L370 I see the latest version (1.0.5) but on http://packages.ros.org/ros2/ubuntu/lists/ros-foxy-focal-amd64_focal_main_amd64_Packages it's still not updated. Not sure when the next release is. Will keep an eye on that.

**Comment by lucabonamini** [comment] 2021-12-30 20:22
Any updates?

**Comment by ahtsan** [comment] 2021-12-30 20:36
@lucabonamini According to http://wiki.ros.org/ROS/ReleasingAPackage,
`Packages built are periodically synchronized over to the shadow-fixed and public repositories, so it might take some time (weeks) before your package has made it into the public ROS debian repositories.`
The latest binaries are already built by the build farm and released into the building repositor. However, I don't have an answer when the next sync will happen.

**Comment by ahtsan** [comment] 2022-01-04 02:09
Since there are no action left on our side, I'm closing this issue. Feel free to create a new issue if you have any further question!

**Comment by SteveMacenski** [comment] 2022-01-04 17:27
Did you test the new binaries with shadow fixed https://docs.ros.org/en/rolling/Installation/Testing.html to see if they work now without adding any paths?

**Comment by ahtsan** [comment] 2022-01-04 20:04
Yes, tested in a docker container and it worked

**Comment by SteveMacenski** [comment] 2022-01-11 22:53
Please reopen, you did not run bloom or release it https://github.com/ros/rosdistro/blob/master/rolling/distribution.yaml#L346-L347 its still marked at 1.0.4. Also the new Rolling release does not include it https://discourse.ros.org/t/new-packages-for-ros-2-rolling-ridley-2022-01-11/23766

**Comment by ahtsan** [comment] 2022-01-12 01:39
Apologize for that -- we planned to bloom release the changes on Foxy first, and only bloom release it to Rolling and Galactic when it's tested. It was tested in Foxy. Will follow up on that.

**Comment by SteveMacenski** [comment] 2022-01-12 01:56
thanks!

**Comment by ahtsan** [comment] 2022-01-12 05:00
Rolling: https://github.com/ros/rosdistro/pull/31737
Galactic: https://github.com/ros/rosdistro/pull/31738

**Comment by ahtsan** [comment] 2022-01-31 22:02
Closing the ticket as the package will be updated in the next release: https://discourse.ros.org/t/new-packages-for-ros-2-rolling-ridley-2022-01-28/24067

**Closed as completed by ahtsan** 2022-01-31 22:02 UTC
